=encoding utf-8

=for HTML

<a href='https://travis-ci.com/raku-community-modules/raku-mime-types.svg?branch=master'><img src='https://api.travis-ci.com/raku-community-modules/raku-mime-types.svg?branch=master&status=passed'></a>
=end HTML

=head1 NAME

MIME::Types - determine mime type by file extension

=head1 DESCRIPTION

A Raku (formerly Perl 6) library that reads the mime.types file as used by
many Linux distributions, and web servers, and returns an object
that can be queried by either type or extension.

=head1 SYNOPSIS

    use MIME::Types;
    my $mime = MIME::Types.new("/etc/mime.types");
    my $type = $mime.type('txt'); ## Returns: 'text/plain';
    my @known_extensions = $mime.extensions('application/vnd.ms-excel');
    ## Returns: [ 'xls', 'xlb', 'xlt' ]

=head1 EXAMPLE

An example mime.types is included in the doc/ directory, and is used by
the tests in t/.

=head1 LICENCE

This is licensed under the Artistic 2.0 license

=head1 AUTHOR

Timothy Totten 
http://huri.net/
https://github.com/supernovus/
